import Head from 'next/head'
import { Inter } from '@next/font/google'
import Header from '@/components/Header'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <div>
      <Head>
        <title>Wasath Theekshana</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* Header */}
      <Header />

      {/* Hero */}

      {/* About */}

      {/* Experiences */}

      {/* Skills */}

      {/* Projects */}

      {/* ContactMe */}

    </div>
  )
}
